### PR TITLE
Implement callbacks and streamable subset option

### PR DESCRIPTION
**Pull request by ali1234**
Implements seek and tell callbacks so that the stream encoder can insert metadata at the start of the file.

Implements metadata callback, although currently the callback just receives a blob of cdata.

Makes streamable subset optional to allow the use of the full format settings.

### CODE REVIEW

**Comment by ali1234** [comment]
This is an example of using the new things:

```python3
import numpy as np
import pyflac


class ExampleFLACEncoder(pyflac.StreamEncoder):
    def __init__(self, filename):
        self._filename = filename
        self._output_file = None
        super().__init__(
            write_callback=self.write_callback,
            seek_callback=self.seek_callback,
            tell_callback=self.tell_callback,
            metadata_callback=self.metadata_callback,
            sample_rate=48000,
            blocksize=65535,
            streamable_subset=False,
            verify=True,
        )

    def write_callback(self, buffer: bytes, num_bytes: int, num_samples: int, current_frame: int):
        self._output_file.write(buffer)

    def seek_callback(self, offset):
        print('seek', offset)
        self._output_file.seek(offset)

    def tell_callback(self):
        offset = self._output_file.tell()
        print('tell', offset)
        return offset

    def metadata_callback(self, metadata):
        # Currently this is just a big blob of cdata.
        print('Metadata:', metadata)

    def __enter__(self):
        self._output_file = open(self._filename, 'wb')
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.finish()
        self._output_file.close()

    def write(self, b):
        self.process(np.frombuffer(b, dtype=np.int8))


def main():
    with ExampleFLACEncoder('test.flac') as enc:
        for n in range(100):
            enc.write(b'\x00\xff'*1024)


if __name__ == '__main__':
    main()
```

**Review by joetoddsonos — CHANGES_REQUESTED** [review]
@ali1234 nice work, thanks for the contribution. 

Just a couple of things to update before we can merge 
- Bump the version number in `__init__.py`. It should probably be `2.0.0` since the interface has changed 
- Update the CHANGELOG.md
- Update the examples to use the new `write_callback`
- It would also be great if you could do a similar thing and add seek/tell callbacks to the decoder to keep the symmetry, and rename the `callback` to `read_callback`. Let me know what you think.

**Review by joetoddsonos — APPROVED** [review]
🚢

**Comment by ali1234** [comment]
I have implemented `seek` and `tell` on `StreamDecoder`. However these are not useful unless user also defines the `read` callback. Currently that is not possible as it is handled internal to `StreamDecoder` and as a result the user can't respond to the `seek` callback by seeking on the file pointer, because there is just an internal memory buffer. Fixing this would require completely changing how `StreamDecoder` works. You could not have a `process` method and implementing the `read` callback would become mandatory in user code.

**Comment by joetoddsonos** [comment]
I see, ok well maybe we should revert commit 243203d. As long as both encoder/decoder data callbacks are now called `write_callback` this makes sense. I can take care of this if you're ready to pull this out of draft status and merge in?

**Comment by ali1234** [comment]
I have dropped https://github.com/sonos/pyFLAC/commit/243203d0eda3c5f4ea86dc2b2404a52c5a87dd72 and updated the changelog and version so this can be merged. I would like to make the necessary changes in decoder at some point, but it could be a long time before I get around to it.

**Pull request merged**
